# Analyzing descriptor 
Analyzing CoP variables, extracted from force platform and radar stabilograms

In [111]:
import pandas as pd
import pingouin as pg
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

## Compute variables mean, std and error
- with platform variables as reference
- for dataset 1, by removing the data 5, because different acquisition protocol

In [112]:
df_platform_features = pd.read_csv("../results/tables/dataset1/platform_descriptors.csv", index_col=0)
df_radar_features = pd.read_csv("../results/tables/dataset1/radar_descriptors.csv", index_col=0)

In [113]:
# removing last one, because it's different test condition
df_platform_features = df_platform_features[:-1]
df_radar_features = df_radar_features[:-1]

In [114]:
epsilon = 1e-6
errors = np.abs(df_radar_features - df_platform_features) / (np.abs(df_platform_features) + epsilon) * 100

In [115]:
errors

,mean_value_ML,mean_value_AP,mean_distance_ML,mean_distance_AP,mean_distance_Radius,maximal_distance_ML,maximal_distance_AP,maximal_distance_Radius,rms_ML,rms_AP,...,critical_time_Diffusion_ML,critical_displacement_Diffusion_ML,short_time_scaling_Diffusion_ML,long_time_scaling_Diffusion_ML,short_time_diffusion_Diffusion_AP,long_time_diffusion_Diffusion_AP,critical_time_Diffusion_AP,critical_displacement_Diffusion_AP,short_time_scaling_Diffusion_AP,long_time_scaling_Diffusion_AP
0,3.655163e-08,4.942747e-08,12.522006,9.757965,0.230626,24.977649,1.221032,25.902147,18.168340,9.520378,...,9.574162,34.588947,1.250052,57.953872,36.994317,97.257734,3.827503,42.483967,1.041127,49.260779
1,6.756767e-09,4.333269e-08,9.916810,10.191869,0.048508,2.653169,7.343846,0.832409,7.520506,13.911718,...,0.832749,29.307309,3.899676,31.568973,36.012942,84.658997,1.448318,34.965979,0.960127,52.911623
2,4.609030e-09,7.931570e-09,12.842805,7.222894,3.892279,0.388314,17.247188,17.285496,14.213178,5.410040,...,25.570912,10.615794,1.955579,17.182423,47.176804,95.590970,6.549883,52.161827,2.644637,55.555462
3,6.583624e-09,8.459534e-09,12.176952,28.243517,14.286670,13.651439,3.193959,6.950007,10.079739,24.832258,...,3.386661,30.934302,0.752374,13.936813,48.103812,79.189172,19.935452,45.738514,21.218375,54.418980

In [116]:
summary_df = pd.DataFrame({
    "radar_mean_value": df_radar_features.mean(),
    "radar_std_value":  df_radar_features.std(),
    "platform_mean_value": df_platform_features.mean(),
    "platform_std_value": df_platform_features.std(),
    "mean_error (%)": errors.mean(),
    "std_error (%)": errors.std()
})

summary_df

,radar_mean_value,radar_std_value,platform_mean_value,platform_std_value,mean_error (%),std_error (%)
mean_value_ML,-1.002730e-17,1.488401e-16,6.939633e-17,3.421928e-16,1.362526e-08,1.531526e-08
mean_value_AP,2.342378e-17,1.753592e-16,3.998065e-17,4.446309e-16,2.728782e-08,2.218686e-08
mean_distance_ML,2.069932e+00,5.199669e-01,2.038194e+00,3.507323e-01,1.186464e+01,1.326715e+00
mean_distance_AP,2.190395e+00,2.918581e-01,2.101417e+00,3.063011e-01,1.385406e+01,9.681916e+00
mean_distance_Radius,3.367971e+00,3.336617e-01,3.237962e+00,4.631071e-01,4.614521e+00,6.686781e+00
...,...,...,...,...,...,...
long_time_diffusion_Diffusion_AP,3.854820e+02,4.812001e+02,1.139422e+04,1.936486e+04,8.917422e+01,8.691113e+00
critical_time_Diffusion_AP,1.953463e+00,1.444204e-01,1.910442e+00,1.456845e-01,7.940289e+00,8.263935e+00
critical_displacement_Diffusion_AP,4.175177e+01,1.622054e+01,7.470545e+01,2.776411e+01,4.383757e+01,7.151788e+00
short_time_scaling_Diffusion_AP,9.187015e-01,1.048938e-01,9.686163e-01,1.628765e-02,6.466067e+00,9.865416e+00
long_time_scaling_Diffusion_AP,-1.344706e+00,4.637775e-01,-2.839342e+00,8.354298e-01,5.303671e+01,2.740322e+00

In [117]:
summary_df.to_csv("../results/tables/dataset1/variables_insight.csv")

## Computing variables mean, std, and error of dataset2

In [118]:
def get_descriptors_insight(df_platform_features, df_radar_features, output_file=None):

    epsilon = 1e-6
    errors = np.abs(df_radar_features - df_platform_features) / (np.abs(df_platform_features) + epsilon) * 100

    summary_df = pd.DataFrame({
        "radar_mean_value": df_radar_features.mean(),
        "radar_std_value":  df_radar_features.std(),
        "platform_mean_value": df_platform_features.mean(),
        "platform_std_value": df_platform_features.std(),
        "mean_error (%)": errors.mean(),
        "std_error (%)": errors.std()
    })

    if output_file is not None:
        summary_df.to_csv(output_file)
    
    return summary_df

In [119]:
df_platform_features = pd.read_csv("../results/tables/dataset2/platform_descriptors.csv", index_col=0)
df_radar_features = pd.read_csv("../results/tables/dataset2/radar_descriptors.csv", index_col=0)

In [120]:
selected_features = [
    "mean_velocity_ML_AND_AP",
    "rms_AP",
    "rms_ML",
    "range_ML_AND_AP",
    "confidence_ellipse_area_ML_AND_AP",
    "mean_value_AP",
    "mean_value_ML",
    "mean_frequency_AP",
    "mean_frequency_ML",
    "fractal_dimension_ML_AND_AP",
    "short_time_diffusion_Diffusion_AP",
    "long_time_diffusion_Diffusion_AP",
    "short_time_scaling_Diffusion_AP",
    "short_time_diffusion_Diffusion_ML",
    "long_time_diffusion_Diffusion_ML",
    "short_time_scaling_Diffusion_ML"
]

### for quiet standing acquisition

In [121]:
df_platform = df_platform_features[:7]
df_radar = df_radar_features[:7]
results = get_descriptors_insight(df_platform, df_radar, "../results/tables/dataset2/variables_insight1.csv")

In [122]:
results.loc[selected_features]

,radar_mean_value,radar_std_value,platform_mean_value,platform_std_value,mean_error (%),std_error (%)
mean_velocity_ML_AND_AP,4.438633e+01,2.700217e+01,1.419975e+00,6.965737e-01,3.609816e+03,2.622724e+03
rms_AP,7.485549e+01,5.248687e+01,8.477989e-01,5.728235e-01,1.193942e+04,1.081016e+04
rms_ML,1.697588e+01,7.784272e+00,5.731011e-01,2.104504e-01,3.768558e+03,4.029714e+03
range_ML_AND_AP,2.934965e+02,1.780078e+02,4.456725e+00,2.878022e+00,8.556260e+03,6.612904e+03
confidence_ellipse_area_ML_AND_AP,2.028895e+04,1.670893e+04,9.704058e+00,8.969189e+00,4.520667e+05,6.322820e+05
mean_value_AP,-8.625745e-15,1.818897e-14,6.829462e-17,2.554566e-16,1.163885e-06,1.609979e-06
mean_value_ML,-7.071774e-16,2.844737e-15,6.457739e-17,4.844475e-16,2.424066e-07,2.122640e-07
mean_frequency_AP,1.077991e-01,2.678065e-02,2.610005e-01,3.721914e-02,5.804085e+01,1.194285e+01
mean_frequency_ML,1.804409e-01,6.848432e-02,3.267169e-01,9.941615e-02,5.317482e+01,1.807737e+01
fractal_dimension_ML_AND_AP,1.473287e+00,6.950105e-02,1.632778e+00,6.505774e-02,9.848556e+00,5.756783e+00
short_time_diffusion_Diffusion_AP,2.273355e+03,2.069397e+03,1.646783e+00,2.624941e+00,4.463730e+05,4.681223e+05
long_time_diffusion_Diffusion_AP,2.536710e+03,2.554681e+03,1.212568e+00,1.859993e+00,7.377325e+05,7.268438e+05
short_time_scaling_Diffusion_AP,9.216986e-01,2.801826e-02,9.012375e-01,1.074612e-02,3.745839e+00,1.747937e+00
short_time_diffusion_Diffusion_ML,2.687951e+02,1.842429e+02,6.953714e-01,5.909614e-01,7.285447e+04,1.016849e+05
long_time_diffusion_Diffusion_ML,2.232662e+02,1.112836e+02,4.265747e-01,2.205903e-01,8.281958e+04,8.949167e+04
short_time_scaling_Diffusion_ML,9.037210e-01,2.146457e-02,8.726304e-01,1.742919e-02,3.900006e+00,2.883150e+00

### for simulated large movement acquisition

In [123]:
df_platform = df_platform_features[8:]
df_radar = df_radar_features[8:]
results = get_descriptors_insight(df_platform, df_radar, "../results/tables/dataset2/variables_insight2.csv")

In [124]:
results.loc[selected_features]

,radar_mean_value,radar_std_value,platform_mean_value,platform_std_value,mean_error (%),std_error (%)
mean_velocity_ML_AND_AP,4.869652e+00,4.641904e-01,5.951890e+00,7.624668e-01,1.762534e+01,7.836703e+00
rms_AP,1.732151e+00,2.191775e-01,1.794757e+00,1.913920e-01,9.344834e+00,4.353187e+00
rms_ML,2.088448e+00,3.863485e-01,2.034135e+00,1.452157e-01,1.120083e+01,1.143481e+01
range_ML_AND_AP,1.123502e+01,2.640096e+00,8.541263e+00,1.019213e+00,3.019263e+01,1.688533e+01
confidence_ellipse_area_ML_AND_AP,5.217749e+01,1.784841e+01,6.863071e+01,1.032374e+01,3.193000e+01,1.487961e+01
mean_value_AP,3.639064e-17,9.695729e-17,2.790299e-16,3.860166e-16,3.089709e-08,3.491393e-08
mean_value_ML,-6.275347e-17,6.347952e-16,2.540314e-16,4.381766e-16,7.365908e-08,7.543632e-08
mean_frequency_AP,3.770776e-01,4.872235e-02,3.918647e-01,3.941071e-02,5.141824e+00,3.946251e+00
mean_frequency_ML,3.797499e-01,5.423444e-02,4.015853e-01,3.675663e-02,6.405725e+00,7.817408e+00
fractal_dimension_ML_AND_AP,1.787007e+00,9.329651e-02,1.801188e+00,4.234165e-02,1.947277e+00,2.180542e+00
short_time_diffusion_Diffusion_AP,9.631910e+00,2.367606e+00,1.512734e+01,5.291748e+00,3.396685e+01,9.816074e+00
long_time_diffusion_Diffusion_AP,3.365437e+00,1.632873e+00,5.017405e+00,1.899932e+00,3.112268e+01,3.141566e+01
short_time_scaling_Diffusion_AP,9.795386e-01,2.273142e-03,9.623008e-01,6.235490e-03,1.795499e+00,8.297548e-01
short_time_diffusion_Diffusion_ML,1.357301e+01,2.767183e+00,2.031724e+01,2.957152e+00,3.292448e+01,1.110354e+01
long_time_diffusion_Diffusion_ML,2.815874e+00,1.872085e+00,3.923475e+00,2.272160e+00,2.897034e+01,1.319297e+01
short_time_scaling_Diffusion_ML,9.797729e-01,2.394162e-03,9.733573e-01,3.144446e-03,6.597614e-01,3.442585e-01